In [1]:
pip install sentence-transformers

Defaulting to user installation because normal site-packages is not writeable
Collecting sentence-transformers
  Downloading sentence_transformers-5.1.2-py3-none-any.whl.metadata (16 kB)
Collecting transformers<5.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-4.57.3-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: tqdm in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (2.6.0)
Requirement already satisfied: scikit-learn in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (1.13.1)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Downloading huggingface_hub-1.3.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: Pillow in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (3.19.1)
  Downloading huggingface_hub-0.36.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Collecting regex!=2019.12.17 (from transformers<5.0.0,>=4.41.0->sentence-transformers)
  Downloading regex-2025.11.3-cp39-cp39-macosx_11_0_arm64.whl.metadata (40 kB)
Requirement already satisfied: requests in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.32.5)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<5.0.0,>=4.41.0->sentence-transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-macosx_11_0_arm64.whl.metadata (7.3 kB)
Collecting safetensors>=0.4.3 (from transformers<5.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl.metadata (4.1 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.10.0)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading hf_xet-1.2.0-cp37-abi3-macosx_11_0_arm64.whl.metadata (4.9 kB)
Requirement already satisfied: networkx in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from torch>=1.11.0->sentence-transformers) (3.2.1)
Requirement already satisfied: jinja2 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: sympy==1.13.1 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.11.12)
Requirement already satisfied: joblib>=1.2.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Downloading sentence_transformers-5.1.2-py3-none-any.whl (488 kB)
Downloading transformers-4.57.3-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 24.4 MB/s  0:00:00eta 0:00:01
Downloading huggingface_hub-0.36.0-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.1/566.1 kB 7.5 MB/s  0:00:00
Downloading hf_xet-1.2.0-cp37-abi3-macosx_11_0_arm64.whl (2.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 36.1 MB/s  0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-macosx_11_0_arm64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 34.2 MB/s  0:00:00
Downloading regex-2025.11.3-cp39-cp39-macosx_11_0_arm64.whl (288 kB)
Downloading safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl (447 kB)
Installing collected packages: safetensors, regex, hf-xet, huggingface-hub, tokenizers, transformers, sentence-transformers
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [sentence-transformers]ence-transformers]
Successfully installed hf-xet-1.2.0 huggingface-hub-0.36.0 regex-2025.11.3 safetensors-0.7.0 sentence-transformers-5.1.2 tokenizers-0.22.2 transformers-4.57.3
Note: you may need to restart the kernel to use updated packages.

In [2]:
import json
import pandas as pd
import numpy as np
from pathlib import Path

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

/Users/lennartredlich/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/lennartredlich/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

i searched for "embedded based labeling sentence transformers" and came across the all-MiniLM-L6-v2 Sentence Transformer, so lets have a look at that

In [6]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [4]:
dept_labels = [
    "Marketing",
    "Sales",
    "Project Management",
    "IT",
    "Finance",
    "HR",
    "Other"
]

In [7]:
dept_label_embeddings = model.encode(dept_labels)

In [8]:
PROJECT_ROOT = Path.cwd().parents[1]
DATA_PATH = PROJECT_ROOT / "files"

with open(DATA_PATH / "linkedin-cvs-annotated.json", "r", encoding="utf-8") as f:
    cvs = json.load(f)

jobs = []
for cv in cvs:
    for job in cv:
        if job["status"] == "ACTIVE":
            jobs.append(job)

df_active = pd.DataFrame(jobs)
df_active.head()

,organization,linkedin,position,startDate,endDate,status,department,seniority
0,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,Prokurist,2019-08,None,ACTIVE,Other,Management
1,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,CFO,2019-07,None,ACTIVE,Other,Management
2,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,Betriebswirtin,2019-07,None,ACTIVE,Other,Professional
3,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,Prokuristin,2019-07,None,ACTIVE,Other,Management
4,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,CFO,2019-07,None,ACTIVE,Other,Management

In [9]:
job_embeddings = model.encode(df_active["position"].astype(str).tolist())

In [10]:
similarity_matrix = cosine_similarity(job_embeddings, dept_label_embeddings)

In [11]:
best_label_idx = similarity_matrix.argmax(axis=1)
df_active["department_pred_embedding"] = [dept_labels[i] for i in best_label_idx]

In [ ]:
df_active[["position", "department", "department_pred_embedding"]].head(10)

,position,department,department_pred_embedding
0,Prokurist,Other,HR
1,CFO,Other,Finance
2,Betriebswirtin,Other,IT
3,Prokuristin,Other,HR
4,CFO,Other,Finance
5,Solutions Architect,Information Technology,Project Management
6,Medizintechnik Beratung,Consulting,Marketing
7,Director expansión de negocio.,Business Development,Project Management
8,Gerente comercial,Sales,Marketing
9,Administrador Unico,Administrative,HR

In [13]:
embedding_accuracy = (
    df_active["department"] == df_active["department_pred_embedding"]
).mean()

embedding_accuracy

np.float64(0.11717495987158909)

In [14]:
df_active[
    df_active["department"] != df_active["department_pred_embedding"]
][["position", "department", "department_pred_embedding"]].head(20)

,position,department,department_pred_embedding
0,Prokurist,Other,HR
1,CFO,Other,Finance
2,Betriebswirtin,Other,IT
3,Prokuristin,Other,HR
4,CFO,Other,Finance
5,Solutions Architect,Information Technology,Project Management
6,Medizintechnik Beratung,Consulting,Marketing
7,Director expansión de negocio.,Business Development,Project Management
8,Gerente comercial,Sales,Marketing
9,Administrador Unico,Administrative,HR
10,"APL-ansvarig, samordning",Administrative,Sales
12,Lab-Supervisor,Other,HR
13,Human Resources Generalist,Human Resources,HR
14,Managing Director,Other,Project Management
15,Set Lighting,Other,IT
16,Set Lighting,Other,IT
17,Set Lighting,Other,IT
18,Set Lighting,Other,IT
19,Set Lighting,Other,IT
21,Leistungssachbearbeiter SGB II,Other,Sales

So we can see that the department Label "Other" dominates. This is the main couse of the low accuracy. Maybe we should get the Label Other correct.

As an optional extension, we take the information from previous positions to provide additional context for active roles labeled as "Other", because its unlikely to change the Department.

Lets only look at the historical jobs which have no Label "Other" and which are INACTIVE

In [ ]:
from collections import Counter
len(cvs)

def dept_from_history(cvs):
    past_departments = [
        job["department"]
        for job in cvs
        if job["status"] == "INACTIVE" and job["department"] != "Other"
    ]

    if not past_departments:   # If there are no historical Jobs with clear Department return None
        return None
    most_common, count = Counter(past_departments).most_common(1)[0]
    return most_common

In [ ]:
rows = []

for cv in cvs:  # cv = eine Person
    
    active_jobs = [
        job for job in cv
        if job["status"] == "ACTIVE"
    ]
    
    if not active_jobs:
        continue  
    
    active_job = active_jobs[0]  
    
    
    if active_job["department"] != "Other":
        continue
    
    inferred_dept = dept_from_history(cv)
    
    rows.append({
        "position": active_job["position"],
        "original_department": active_job["department"],
        "inferred_department_from_history": inferred_dept
    })

In [24]:
df_other_extension["inferred_department_from_history"].notna().mean()

np.float64(0.496)

In [25]:
active_counts = [sum(1 for job in cv if job["status"] == "ACTIVE") for cv in cvs]
pd.Series(active_counts).value_counts().head(10)

1     380
0     131
2      78
3      10
5       4
4       3
8       1
7       1
10      1
Name: count, dtype: int64