In [28]:
pip install sentence-transformers

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (5.1.2)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (4.57.3)
Requirement already satisfied: tqdm in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (2.6.0)
Requirement already satisfied: scikit-learn in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (0.36.0)
Requirement already satisfied: Pillow in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (3.19.1)
Requirement already satisfied: numpy>=1.17 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: requests in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.2.0)
Requirement already satisfied: networkx in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from torch>=1.11.0->sentence-transformers) (3.2.1)
Requirement already satisfied: jinja2 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: sympy==1.13.1 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.11.12)
Requirement already satisfied: joblib>=1.2.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/lennartredlich/Library/Python/3.9/lib/python/site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [29]:
import json
import pandas as pd
import numpy as np
from pathlib import Path

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

i searched for "embedded based labeling sentence transformers" and came across the all-MiniLM-L6-v2 Sentence Transformer, so lets have a look at that

In [30]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [31]:
dept_labels = [
    "Marketing",
    "Sales",
    "Project Management",
    "IT",
    "Finance",
    "HR",
    "Other"
]

In [32]:
dept_label_embeddings = model.encode(dept_labels)

In [33]:
PROJECT_ROOT = Path.cwd().parents[1]
DATA_PATH = PROJECT_ROOT / "files"

with open(DATA_PATH / "linkedin-cvs-annotated.json", "r", encoding="utf-8") as f:
    cvs = json.load(f)

jobs = []
for person_id, cv in enumerate(cvs):
    for job in cv:
        if job["status"] == "ACTIVE":
            jobs.append({
                **job,
                "person_id": person_id
            })

df_active = pd.DataFrame(jobs)
df_active.head()

,organization,linkedin,position,startDate,endDate,status,department,seniority,person_id
0,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,Prokurist,2019-08,None,ACTIVE,Other,Management,0
1,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,CFO,2019-07,None,ACTIVE,Other,Management,0
2,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,Betriebswirtin,2019-07,None,ACTIVE,Other,Professional,0
3,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,Prokuristin,2019-07,None,ACTIVE,Other,Management,0
4,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,CFO,2019-07,None,ACTIVE,Other,Management,0

In [34]:
job_embeddings = model.encode(df_active["position"].astype(str).tolist())

In [35]:
similarity_matrix = cosine_similarity(job_embeddings, dept_label_embeddings)

In [36]:
best_label_idx = similarity_matrix.argmax(axis=1)
df_active["department_pred_embedding"] = [dept_labels[i] for i in best_label_idx]

In [37]:
df_active[["position", "department", "department_pred_embedding"]].head(10)

,position,department,department_pred_embedding
0,Prokurist,Other,HR
1,CFO,Other,Finance
2,Betriebswirtin,Other,IT
3,Prokuristin,Other,HR
4,CFO,Other,Finance
5,Solutions Architect,Information Technology,Project Management
6,Medizintechnik Beratung,Consulting,Marketing
7,Director expansión de negocio.,Business Development,Project Management
8,Gerente comercial,Sales,Marketing
9,Administrador Unico,Administrative,HR

So we can see that the department Label "Other" dominates. This is the main couse of the low accuracy. Maybe we should get the Label Other correct.

As an optional extension, we take the information from previous positions to provide additional context for active roles labeled as "Other", because its unlikely to change the Department.

Lets only look at the historical jobs which have no Label "Other" and which are INACTIVE

In [38]:
from collections import Counter

def dept_from_history(cv):
    past_departments = [
        job["department"]
        for job in cv
        if job["status"] == "INACTIVE" and job["department"] != "Other"
    ]
    if not past_departments:
        return None
    return Counter(past_departments).most_common(1)[0][0]

In [39]:
person_to_inferred = {}

for person_id, cv in enumerate(cvs):
    inferred = dept_from_history(cv)
    if inferred is not None:
        person_to_inferred[person_id] = inferred

In [40]:
df_active["department_fixed"] = df_active["department"]

mask_other = df_active["department_fixed"] == "Other"

df_active.loc[mask_other, "department_fixed"] = (
    df_active.loc[mask_other, "person_id"]
    .map(person_to_inferred)
    .fillna("Other")
)

In [41]:
changed_rate = (df_active["department"] != df_active["department_fixed"]).mean()

coverage_other = (
    df_active.loc[df_active["department"] == "Other", "department_fixed"]
    .ne("Other")
    .mean()
)

changed_rate, coverage_other

(np.float64(0.27287319422150885), np.float64(0.4941860465116279))

In [42]:
embedding_accuracy_history = (
    df_active["department_fixed"] == df_active["department_pred_embedding"]
).mean()

embedding_accuracy_history

np.float64(0.11556982343499198)

In [43]:
HIGH_LEVEL_MAP = {
    # Tech
    "IT": "Tech",
    "Information Technology": "Tech",

    # Commercial
    "Marketing": "Commercial",
    "Sales": "Commercial",
    "Business Development": "Commercial",
    "Project Management": "Commercial",
    "Consulting": "Commercial",

    # Corporate
    "HR": "Corporate",
    "Human Resources": "Corporate",
    "Finance": "Corporate",
    "Administrative": "Corporate",

    # Other
    "Other": "Other"
}

In [44]:
df_active["department_fixed_cluster"] = df_active["department_fixed"].map(HIGH_LEVEL_MAP)
df_active["department_pred_cluster"] = df_active["department_pred_embedding"].map(HIGH_LEVEL_MAP)

In [45]:
hierarchical_accuracy = (
    df_active["department_fixed_cluster"] ==
    df_active["department_pred_cluster"]
).mean()

hierarchical_accuracy

np.float64(0.36436597110754415)

In [46]:
df_active[[
    "person_id",
    "position",
    "department",                  # ursprüngliche Wahrheit
    "department_fixed",            # nach History-Fix
    "department_pred_embedding"    # Modell
]].head(40)

,person_id,position,department,department_fixed,department_pred_embedding
0,0,Prokurist,Other,Other,HR
1,0,CFO,Other,Other,Finance
2,0,Betriebswirtin,Other,Other,IT
3,0,Prokuristin,Other,Other,HR
4,0,CFO,Other,Other,Finance
5,1,Solutions Architect,Information Technology,Information Technology,Project Management
6,2,Medizintechnik Beratung,Consulting,Consulting,Marketing
7,3,Director expansión de negocio.,Business Development,Business Development,Project Management
8,3,Gerente comercial,Sales,Sales,Marketing
9,3,Administrador Unico,Administrative,Administrative,HR
10,4,"APL-ansvarig, samordning",Administrative,Administrative,Sales
11,5,Kaufmännischer Leiter,Sales,Sales,Sales
12,6,Lab-Supervisor,Other,Other,HR
13,7,Human Resources Generalist,Human Resources,Human Resources,HR
14,8,Managing Director,Other,Other,Project Management
15,11,Set Lighting,Other,Other,IT
16,11,Set Lighting,Other,Other,IT
17,11,Set Lighting,Other,Other,IT
18,11,Set Lighting,Other,Other,IT
19,11,Set Lighting,Other,Other,IT
20,12,Projektmanager,Project Management,Project Management,Project Management
21,13,Leistungssachbearbeiter SGB II,Other,Other,Sales
22,14,energy and sustainability consultant bei,Consulting,Consulting,Project Management
23,15,Purchasing Manager,Purchasing,Purchasing,Sales
24,16,Geschäftsführer,Other,Other,HR
25,18,Senior Project Manager,Project Management,Project Management,Project Management
26,20,Dr. phil.,Other,Other,HR
27,21,"Geschäftsführer, CMO",Marketing,Marketing,Finance
28,21,Geschäftsführender Gesellschafter,Other,Marketing,Project Management
29,22,Bereichsleiter Maschinen,Other,Other,Marketing
30,23,Principal RF Design Engineer,Information Technology,Information Technology,Project Management
31,24,Physician Assistant,Other,Other,HR
32,27,Co-Owner,Other,Sales,Sales
33,27,CEO,Other,Sales,Marketing
34,27,CEO/Founder,Other,Sales,Marketing
35,30,Qualifizierter Kreditsachbearbeiter im risikor...,Other,Other,Marketing
36,31,Director,Other,Business Development,HR
37,32,IT Systems and Network Engineer,Information Technology,Information Technology,Project Management
38,33,IT-Teamleiter,Information Technology,Information Technology,IT
39,33,Senior IT-Sicherheitsbeauftragter,Information Technology,Information Technology,HR